version = 1

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["Dockerfile"]

[[transformers]]
name = "prettier"
enabled = true